### ISSUE TITLE
openBluetoothSettings appears to be Android only, not iOS only?

### ISSUE THREAD

**Issue by htran-ubed** [general-galactic/capacitor-esp-idf-provisioning#13]
The openBluetoothSettings function does nothing for me on iOS, but it opens the Bluetooth settings on Android. Though in the readme, it says iOS only.

I just checked again and I even get the error on iOS: openBluetoothSettings is not available on iOS.

**Comment by jkennedy1980** [comment]
Yes, just a mixup in the readme. It's been updated.
