### ISSUE TITLE
scanWifiList not returning auth but security

### ISSUE THREAD

**Issue by otiv33** [general-galactic/capacitor-esp-idf-provisioning#15]
When we call scanWifiList it returns:
```
[
   {ssid: 'MySsid1', rssi: -35, security: 0},
   {ssid: 'MySsid2', rssi: -25, security: 3}
   ...
]
```
The return type for scanWifiList is `Promise<{ networks?: ESPNetwork[] }>`. `ESPNetwork `has a property `auth` which does not return anything (maybe it was changed for `security` recently). 

For the wifi security type reference which number is which type i found a helpful [repo](https://github.com/orbital-systems/react-native-esp-idf-provisioning).

I am connecting to an espressif esp32.

**Comment by otiv33** [comment]
Made a [PR](https://github.com/general-galactic/capacitor-esp-idf-provisioning/pull/16) with the suggested changes

**Comment by jolson474** [comment]
I don't see that output when calling this library.  When I scan, I  get back `auth` properties populated with strings : 
```
[
    {"rssi":-36,"auth":"wpa2psk","ssid":"redacted1"},
    {"ssid":"redacted2","rssi":-80,"auth":"wpa2psk"},
    {"rssi":-72,"auth":"wpa2Wpa3Psk","ssid":"redacted3"},
    {"auth":"wpa2psk","rssi":-86,"ssid":"redacted4"},
    {"auth":"wpa2psk","rssi":-85,"ssid":"redacted5"},
    {"auth":"wpa2psk","ssid":"redacted6","rssi":-90},
    {"ssid":"redacted7","auth":"wpa2psk","rssi":-86},
    {"auth":"wpa2psk","ssid":"redacted8","rssi":-79},
    {"ssid":"redacted9","auth":"wpa2psk","rssi":-86}
]
```

When doing that, I am running this Ionic code on an iOS device:
```ts
import {  EspProvisioning } from '@general-galactic/capacitor-esp-idf-provisioning'
const { networks } = await EspProvisioning.scanWifiList({ deviceName: this.deviceName })
console.log(networks)
```

By any chance, did you dump a different object in the call stack or something?  The underlying `ESPProvision` library does use an integer enumeration for that field under the hood I believe.

**Comment by jolson474** [comment]
Oh wait... too funny.  Android does exactly what you say.  Let me dig in

**Comment by jolson474** [comment]
Fixed bug so Android is now correctly returning `auth` on `0.0.97`
