### ISSUE TITLE
Feature Scan device QR code

### ISSUE THREAD

**Issue by macielcr7** [general-galactic/capacitor-esp-idf-provisioning#3]
there is the possibility to add the QRCode option passing the UIView???

**Scan**

Device information can be extracted from scanning valid QR code. User of this API decides the camera preview layer frame by providing UIView as parameter. It return single ESPDevice instance on success. Supports both SoftAP and BLE.

`ESPProvisionManager.shared.scanQRCode(scanView: scannerView) { espDevice, _ in}`

**Comment by jkennedy1980** [comment]
I don't have time to implement this right now but will accept tested pull requests.
