### ISSUE TITLE
Supporting Security2

### ISSUE THREAD

**Issue by KLaci** [general-galactic/capacitor-esp-idf-provisioning#4]
Hi,

Thanks for this great library! 
Are there any plans to support Security2 in it? I noticed that Espressif has added support for it in the latest version of their library. https://github.com/espressif/esp-idf-provisioning-android/releases/tag/Provisioning_App_Release_2.1.0

Laszlo

**Comment by peti01** [comment]
+1

**Comment by jkennedy1980** [comment]
Have you tested it with Sec2? This project uses a fork of espressif/esp-idf-provisioning-android. I just checked and my fork is only 3 commits behind master. I believe it should support Sec2 and if it doesn't there must be something else wrong.

**Comment by KLaci** [comment]
I didn't have the chance to test it thoroughly, but it seems that the only missing step was setting the username during the connection, which is required by Security2. I added it, and it appears to be working for me now. By the way, thanks for the great library!
