### ISSUE TITLE
Android SDK Version support

### ISSUE THREAD

**Issue by franriibeiro** [general-galactic/capacitor-esp-idf-provisioning#5]
Hello,

I have been testing your plugin with two android devices (version 9 and 13) and i'm encountering several permission problems in the android 9 phone. Should the plugin also support this lower versions of the android OS or it should only work in versions equal or greater than the 12th version? Or is there any previous release of the plugin that supported older versions of the android OS? 

Thank you

**Comment by jkennedy1980** [comment]
Hello, yes, currently it will only work for android 12 and above. The code to support the old permissions is all there but I don't have time to test it. If you'd like to help, we can probably get it working for older versions.

You could try the older builds to see if they work but they will probably not work on devices newer than 12.

**Comment by franriibeiro** [comment]
Thank you very much for your response. I have been doing some experiments in older builds and if i can put something working i will message you.

**Comment by jkennedy1980** [comment]
Ok, I fixed the library so that it should work back to SDK 25 ( Android 7 ). I've tested on Android 11 and Android 13.
