### ISSUE TITLE
no npn package available

### ISSUE THREAD

**Issue by ClemensEy** [general-galactic/capacitor-esp-idf-provisioning#6]
> npm install @general-galactic/capacitor-esp-idf-provisioning
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@general-galactic%2fcapacitor-esp-idf-provisioning - Not found
npm ERR! 404
npm ERR! 404  '@general-galactic/capacitor-esp-idf-provisioning@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by mwyld** [comment]
Hi, this plugin looks great! However, I'm getting the same as @ClemensEy it doesn't appear to be on npm

**Comment by mwyld** [comment]
I found it here https://www.npmjs.com/package/cap-esp-idf however I'm getting the following when doing `npx cap sync`

```
✖ update ios - failed!
[error] Analyzing dependencies
        [!] No podspec found for `CapEspIdf` in `../../node_modules/cap-esp-idf`
```

**Comment by jkennedy1980** [comment]
I've regained access to our NPM organization and published this module. No more configuring NPM to pull from github packages.

**Comment by jkennedy1980** [comment]
> I found it here https://www.npmjs.com/package/cap-esp-idf however I'm getting the following when doing `npx cap sync`
> 
> ```
> ✖ update ios - failed!
> [error] Analyzing dependencies
>         [!] No podspec found for `CapEspIdf` in `../../node_modules/cap-esp-idf`
> ```

That package was not published by me. That was someone publishing to NPM under a different name. Please install the official package and see if you get the same issue.
