### ISSUE TITLE
fails to connect to device

### ISSUE THREAD

**Issue by mwyld** [general-galactic/capacitor-esp-idf-provisioning#7]
Hey again,

I've moved over to this npm package but I'm getting the following error:

no code my end has been changed and this works in the 'cap-esp-idf' package.

```{code: "connect-error-1", errorMessage: "Failed to connect to device: PROV_123456 Optional(ESPProvision.ESPSessionError.noUsername)", message: "Failed to connect to device: PROV_123456 Optional(ESPProvision.ESPSessionError.noUsername)"}```

'cap-esp-idf' has some other bugs, so would prefer to use this if it's supported

**Comment by mwyld** [comment]
sorry, let me give you a little more on this, I'm using the `connect` method and sending a valid device name and `proofOfPossession`. I am using the ESP-S3 and the firmware is flashed with the wifi provisioning example supplied by Expressif. Please let me know if you'd like any more info

**Comment by jkennedy1980** [comment]
So, I'd need to see a lot of code to be able to help. Be sure the `devicePrefix` your're using matches the prefix configured in your firmware. In the example above `PROV`.

**Comment by jkennedy1980** [comment]
Without more info there's not much I can do
