### ISSUE TITLE
authMode switch must be exhaustive

### ISSUE THREAD

**Issue by gregor-srdic** [general-galactic/capacitor-esp-idf-provisioning#8]
Building @capacitor/ios 5.6.0 app with nodejs 18.19.0 and Xcode 14.2 I get the following error:

▸ Generating 'SwiftProtobuf.framework.dSYM'
▸ Touching SwiftProtobuf.framework (in target 'SwiftProtobuf' from project 'Pods')
▸ Processing ESPProvision-Info.plist
▸ Compiling ESPProvision_vers.c
▸ Compiling ESPProvision-dummy.m
▸ Copying GeneralGalacticCapacitorEspIdfProvisioning-umbrella.h
▸ Copying EspProvisioningPlugin.h
▸ Linking ESPProvision

❌  /Users/runner/work/1/s/node_modules/@general-galactic/capacitor-esp-idf-provisioning/ios/Plugin/EspProvisioningPlugin.swift:293:9: switch must be exhaustive

        switch authMode {
                                       ^

▸ Generating 'ESPProvision.framework.dSYM'
    Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
** BUILD FAILED **

**Comment by jkennedy1980** [comment]
Fixed in version 1.0.93 - Thanks for the fix @gregor-srdic.
